// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzF1bqzmF9MZRfcvnQpz7AEkuf76910nM',
    appId: '1:546635066871:web:b8f016b344ca766e9752f2',
    messagingSenderId: '546635066871',
    projectId: 'todo-application-by-saa',
    authDomain: 'todo-application-by-saa.firebaseapp.com',
    storageBucket: 'todo-application-by-saa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz2cx4Rj6U9L4VjZxRODf81JPZoTysLZk',
    appId: '1:546635066871:android:8271de73e0efb4ed9752f2',
    messagingSenderId: '546635066871',
    projectId: 'todo-application-by-saa',
    storageBucket: 'todo-application-by-saa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdkASG-J_EnQxkpv2gfER-qgmpaoK4RLo',
    appId: '1:546635066871:ios:94deee58a354117d9752f2',
    messagingSenderId: '546635066871',
    projectId: 'todo-application-by-saa',
    storageBucket: 'todo-application-by-saa.appspot.com',
    iosBundleId: 'com.example.hackathon1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdkASG-J_EnQxkpv2gfER-qgmpaoK4RLo',
    appId: '1:546635066871:ios:9a627c1393eb5dd29752f2',
    messagingSenderId: '546635066871',
    projectId: 'todo-application-by-saa',
    storageBucket: 'todo-application-by-saa.appspot.com',
    iosBundleId: 'com.example.hackathon1.RunnerTests',
  );
}
